### ISSUE TITLE
Wāpuro rōmaji

### ISSUE THREAD

**Issue by amnek0** [nihongodera/limelight#8]
can we have another style(waapuro) for romaji conversion?

```
waapuro

週末　＝　shuumatsu
土曜日　= doyoubi
```

```
Hepburn

週末　＝　shūmatsu
土曜日　=　doyōbi
```

[https://www.sljfaq.org/afaq/wapuro-romaji.html](https://www.sljfaq.org/afaq/wapuro-romaji.html)

**Comment by zachleigh** [comment]
@amnek0 
Sorry about the late response on this. Been very busy lately. 

Wapuro romaji support was added in v1.6.6. I didn't add it earlier because there is no clear specification for it. However, outside of the weird combinations (どぁ for example), its fairly standard so I added what seems right to me. If you find problems in it, let me know.
